[package]
name = "nabla"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5"
num = "0.4"
rayon = {version = "1.6", optional = true }

[features]
default = ["rayon"]
rayon = ["dep:rayon"]